# Generated by Django 4.0.3 on 2022-04-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobs_arquivo_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='categoria',
        ),
        migrations.AddField(
            model_name='jobs',
            name='categorias',
            field=models.CharField(choices=[('D', 'Design'), ('EV', 'Edição de Vídeo'), ('MD', 'Marketing Digital'), ('LP', 'Landing Page')], default='D', max_length=4),
        ),
    ]
